#dashboard database
CREATE DATABASE dashboard;
DROP TABLE dashboard.articles;

CREATE TABLE dashboard.users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100),
username BLOB not null,
password VARCHAR(100),
permissions VARCHAR(30) DEFAULT 'user',
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
UNIQUE KEY `u_k_1`(username(30))
 );

CREATE TABLE dashboard.articles (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255),
author VARCHAR(100),
body TEXT,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
